version: '3'
services:
  # nodejs-server:
  #   build:
  #     context: ./api
  #   ports:
  #     - "3080:3080"
  #   container_name: node-api
  #   volumes:
  #      - ./api:/usr/src/app/api
  #      - /usr/src/app/api/node_modules
  frontend:
    build:
      context: .
    ports:
      - "4001:3000"
    container_name: lms-frontend
    stdin_open: true
    volumes:
       - .:/app
       - /app/node_modules